# Generated by Django 2.2.2 on 2019-06-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Research_field', models.CharField(max_length=50)),
                ('paper_type', models.CharField(max_length=50)),
                ('attachment', models.FileField(upload_to='')),
                ('Keywords', models.TextField()),
                ('Author', models.TextField()),
                ('Created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_id', models.IntegerField()),
                ('Transaction_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=50)),
                ('contect', models.IntegerField()),
                ('Designation', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Bio', models.TextField()),
            ],
        ),
    ]
