# Generated by Django 2.2.2 on 2019-07-06 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_id', models.IntegerField()),
                ('Transaction_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Contect', models.IntegerField()),
                ('Designation', models.CharField(choices=[('a', 'student'), ('b', 'professional'), ('c', 'other')], max_length=50)),
                ('Organisation', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Research_field', models.CharField(max_length=50)),
                ('paper_type', models.CharField(max_length=50)),
                ('attachment', models.FileField(upload_to='documents/')),
                ('Keywords', models.TextField()),
                ('Author', models.TextField()),
                ('Created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.profile')),
            ],
        ),
    ]
