# Generated by Django 2.2.2 on 2019-07-07 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0002_auto_20190707_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='User',
            new_name='profil',
        ),
        migrations.AddField(
            model_name='paper',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
