# Generated by Django 2.2.2 on 2019-07-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20190702_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Designation',
            field=models.CharField(choices=[('a', 'student'), ('b', 'professional'), ('c', 'other')], max_length=50),
        ),
    ]
