# Generated by Django 2.2.2 on 2019-07-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20190707_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='user',
        ),
    ]
