# Generated by Django 2.2.2 on 2019-07-02 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20190702_0404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contect',
            new_name='Contect',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='organisation',
            new_name='Organisation',
        ),
    ]
