# Generated by Django 2.2.2 on 2019-07-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_remove_paper_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
