# Generated by Django 2.2.2 on 2019-07-04 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20190703_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='research.profile'),
        ),
    ]
